services:
  portabase:
    container_name: portabase
    image: portabase/portabase:latest
    restart: always
    environment:
      - TZ=America/New_York
      - PROJECT_NAME
      - PROJECT_URL
      - PROJECT_SECRET
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_HOST
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@portabase-pg:5432/${POSTGRES_DB}?schema=public
      - SMTP_HOST
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASSWORD
      - SMTP_FROM
    ports:
      - "${HOST_PORT}:80"
    volumes:
      - ${DATA_DIR=-./data}:/data
    depends_on:
      portabase-pg:
        condition: service_healthy
    networks:
      - portabase_internal
      - newt_net

  portabase-pg:
    container_name: portabase-pg
    image: postgres:17-alpine
    restart: always
    volumes:
      - ${DB_DIR=-./db}:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - portabase_internal

networks:
  portabase_internal:
    name: portabase_internal
    driver: bridge
  newt_net:
    external: true
