services:
  # --------------------------------------------------------------------------------
  # BitMappery
  # A pixel art editor that runs in the browser.
  # --------------------------------------------------------------------------------
  bitmappery:
    image: ghcr.io/formless63/bitmappery:latest
    container_name: bitmappery
    restart: unless-stopped
    logging: *default-logging
    ports:
      - 5173:5173
    environment:
      # BitMappery is a static site served by http-server.
      # It doesn't require complex environment variables.
      NODE_ENV: production
